"""empty message

Revision ID: 482d881f73fe
Revises: 8b9fa1de4781
Create Date: 2025-01-24 12:59:33.331588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482d881f73fe'
down_revision = '8b9fa1de4781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
